### ISSUE TITLE
SBS On demand has stopped

### ISSUE THREAD

**Issue by shavanni** [nextux/sbs-android-tv#8]
After opening the app, the app will crash whilst loading content. 
App version  is 1.2.3. Storage and microphone permissions are set on. 

Error Message is Unfortunately, SBS on demand has stopped. 

Hardware is mibox, Android TV  6.0.1

**Comment by nextux** [comment]
Unfortunately I don't own a minor to be able to test this hardware wise. My Sony Bravia running Android 6.0.1 doesn't have any issues. Can I get you to try 1.2.2 and advise if the result is the same? Also are you using a smart DNS service such as getflix? Having getflix set to the wrong region will throw an error.

**Comment by shavanni** [comment]
Hi Alan

It looks like it may have been server side as its now working again.

Thanks
